# ----------------------------------------------------------------------------
#
# Package             : pypa
# Source Repo         : https://github.com/pypa/packaging
# Travis Job Link     : https://travis-ci.com/github/asellappen/pypa/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python
cache: pip
python: 3.8

matrix:
  include:
    - python: 2.7
      env: NOXSESSION=tests-2.7
    - python: pypy
      env: NOXSESSION=tests-pypy
    - python: pypy3
      env: NOXSESSION=tests-pypy3
    - python: 3.4
      env: NOXSESSION=tests-3.4
    - python: 3.5
      env: NOXSESSION=tests-3.5
    - python: 3.6
      env: NOXSESSION=tests-3.6
    - python: 3.7
      env: NOXSESSION=tests-3.7
    - python: 3.8
      env: NOXSESSION=tests-3.8
    - env: NOXSESSION=lint
    - env: NOXSESSION=docs
    - python: 2.7
      env: NOXSESSION=tests-2.7
      arch: ppc64le
    - python: 3.4
      env: NOXSESSION=tests-3.4
      arch: ppc64le
    - python: 3.5
      env: NOXSESSION=tests-3.5
      arch: ppc64le
    - python: 3.6
      env: NOXSESSION=tests-3.6
      arch: ppc64le
    - python: 3.7
      env: NOXSESSION=tests-3.7
      arch: ppc64le
    - python: 3.8
      env: NOXSESSION=tests-3.8
      arch: ppc64le
    - env: NOXSESSION=lint
      arch: ppc64le
    - env: NOXSESSION=docs
      arch: ppc64le

install:
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
      curl https://pyenv.run | bash;
      export PATH="~/.pyenv/bin:$PATH";
      eval "$(pyenv init -)";
      eval "$(pyenv virtualenv-init -)";
      source ~/.bashrc;
    fi
  - pyenv global 3.7.1
  - python3.7 -m pip install nox

script:
  - python3.7 -m nox

notifications:
  irc:
    channels:
      # This is set to a secure variable to prevent forks from notifying the
      # IRC channel whenever they fail a build. This can be removed when travis
      # implements https://github.com/travis-ci/travis-ci/issues/1094.
      # The actual value here is: irc.freenode.org#pypa-dev
      - secure: "Br6aYBYkjL17fBZ6+AczCkaBMWQAY6To8IH4zqhHrORXAWq4zeuC4VyCZ4MXmDzk0WbA3h3Ea7u9kodUf1sVK1h0q7HX66p8qmFyTncQoLFgo2LF/x1aU1FGWKDDSX5K6qKOzUKrHUhQyVq+uAuRVUm7bJhJL0/viPwEoh+bONo="
    use_notice: true
    skip_join: true
